### ISSUE TITLE
Async/nonblocking mode

### ISSUE THREAD

**Issue by twilligon** [milkey-mouse/openpty#2]
with `O_NONBLOCK`

**Comment by prabirshrestha** [comment]
Could most likely easy accomplish this with [smol](https://github.com/stjepang/smol) 
portable-pty does it https://docs.rs/crate/portable-pty/0.3.0/source/examples/whoami_async.rs

**Comment by twilligon** [comment]
As a library, I probably wouldn't need an executor. It'd boil down to making an `async_openpty` function that returns a future (or an async function returning the regular tuple). It would be up to the consumer to execute it.

**Comment by twilligon** [comment]
In fact, when I wrote this issue `async`/`await` wasn't yet stable or widely adopted, but now that it is, a better solution for tokio users would be to just use [tokio-file-unix](https://docs.rs/tokio-file-unix/0.5.1/tokio_file_unix/struct.File.html#method.new_nb):

```rust
tokio::task::spawn_blocking(move || {
    let (mut master, mut slave, mut name) = openpty::openpty(None, None, None)?;
    let mut master_nb = tokio_file_unix::File::new_nb(master)?;
    let mut slave_nb = tokio_file_unix::File::new_nb(slave)?;

    (master_nb, slave_nb, name)
}).await?;
```

The underlying calls are mostly synchronous anyway, so an async version of `openpty::openpty` wouldn't be for much gain. I'm sure there's something similar for async-std (and smol) as long as they support nonblocking files on Unix.
