### ISSUE TITLE
NotFound error when providing name parameter

### ISSUE THREAD

**Issue by dbrgn** [milkey-mouse/openpty#4]
When I call the function with the `name` parameter...

```diff
--- a/src/main.rs
+++ b/src/main.rs
@@ -2,7 +2,7 @@ use openpty::openpty;
 use std::io::{Read, Write};

 fn main() {
-    let (mut master, mut slave, _) = openpty(None, None, None).unwrap();
+    let (mut master, mut slave, _name) = openpty(None, None, Some(String::new())).unwrap();

     // like a subprocess would, write to slave fd
     println!("I wrote Hello world!");
```

...I get this error message:

```
thread 'main' panicked at 'openpty call failed: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:997:5
```

It seems that the pts device [here](https://github.com/milkey-mouse/openpty/blob/9dc6619d2d09252d503b90faa614592cf319a23e/src/lib.rs#L42-L47) cannot be opened. Any ideas? (Note: I'm not very familiar with how openpty works exactly, my main goal is getting a pseudo-serial device for unit testing in linux-embedded-hal.)

My system: Arch Linux, kernel 5.0.13,

**Comment by twilligon** [comment]
The `name` parameter, if specified, should be the path to a PTY. For example, by default `name` ends up as the first available PTY device. In historical (libc) versions of openpty() this was accomplished by looping until an open device was found: try to open `/dev/pts/0`, then `/dev/pts/1`, then `/dev/pts/2`...

Instead musl openpty(), and this Rust implementation, use some magic ioctls that find and claim/lock said PTY without a loop:

https://github.com/milkey-mouse/openpty/blob/9dc6619d2d09252d503b90faa614592cf319a23e/src/lib.rs#L38-L39

https://github.com/milkey-mouse/openpty/blob/9dc6619d2d09252d503b90faa614592cf319a23e/src/lib.rs#L42

Anyway, chances are you don't want to *set* `name` yourself unless you have a good reason.

The tuple openpty() returns does include the final `name`, though. Chances are this is what you want.

https://github.com/milkey-mouse/openpty/blob/9dc6619d2d09252d503b90faa614592cf319a23e/src/lib.rs#L59

**Comment by dbrgn** [comment]
Thanks!
